- name: "Configure xscreensaver options in '{{ xscreensaver_config_file_path }}'"
  ansible.builtin.template:
    dest: "{{ xscreensaver_config_file_path }}"
    src: "xscreensaver.j2"
    owner: "{{ xscreensaver_user_name }}"
    mode: '644'
    force: true
  become: true
  become_user: root

